language: ruby
rvm:
  - "1.9.3"
  - "2.0.0"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
services: mongodb
bundler_args: --without test development
script: export DISPLAY=:99.0 && bundle exec rake jasmine:ci && bundle exec rake
notifications:
  email:
    recipients:
      - healthcare-ci@googlegroups.com
    on_failure: change
branches: 
  only:
    - master
    - develop